#ifndef _MESSAGE_CODE_H_
#define _MESSAGE_CODE_H_

#define MESSAGE_DIVIDER_EOT 0x04
#define MESSAGE_DIVIDER_ETX 0x03

#define MESSAGE_CODE_SIGN_IN_REQUEST 0xf001
#define MESSAGE_CODE_SIGN_IN_SUCCESS 0xf002
#define MESSAGE_CODE_SIGN_IN_FAILURE 0xf003
#define MESSAGE_CODE_SIGN_UP_REQUEST 0xf004
#define MESSAGE_CODE_SIGN_UP_SUCCESS 0xf005
#define MESSAGE_CODE_SIGN_UP_FAILURE 0xf006


// not implemented yet
// MESSAGE client quit
// message server quit

#endif
